set -g default-terminal "tmux-256color"
set -as terminal-overrides ",alacritty*:Tc"
set -g mouse on
set -g history-limit 10000
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Copy-mode
setw -g mode-keys vi

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# For tmux 2.6 and above: Copy to macOS clipboard automatically on mouse drag
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
